---
#--------------------------------------------------
# Install NGINX
#--------------------------------------------------
- name: Uninstall Nginx Server
  apt:
    name: ["nginx", "nginx-common"]
    state: absent
    purge: yes
    force: yes
  tags: proxy

- name: Install Nginx Server
  apt:
    name: ["nginx", "nginx-common"]
    install_recommends: no
    update_cache: yes
  tags: proxy

- name: Nginx started
  service:
    name: "nginx"
    state: started
  tags: proxy

#--------------------------------------------------
# NGINX Configuration
#--------------------------------------------------
- name: Configure Nginx
  template:
    src: "{{ nginx_template }}.j2"
    dest: "/etc/nginx/sites-available/odoo"
  notify: restart nginx
  tags: proxy, certbot

- import_role:
    name: ansible-role-certbot
  tags: proxy, certbot
  

- name: "Enable nginx configuration"
  file:
    src: "/etc/nginx/sites-available/odoo"
    dest: "/etc/nginx/sites-enabled/odoo"
    state: link
  notify: restart nginx
  tags: proxy, certbot

- name: Remove default Nginx configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: restart nginx
  tags: proxy, certbot
